exclude: [".gitignore", "readme.md", "Gemfile", "Gemfile.lock"]
gems: [jekyll-paginate,jekyll-sitemap, jekyll-seo-tag]

# Setup
author:         griffio
baseurl:
url:            https://griffio.github.io
github:         https://github.com/griffio
name:           griffio
repo:           https://github.com/griffio/griffio.github.io
title:          Griffio
paginate:       31
permalink:      pretty
version:        1.1.1


